version: '3'

#In case you want to setup a traefik configuration, the commented lines are good to pick up on

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: DB
      MYSQL_ROOT_PASSWORD: IlkaMosebach-98712&//
    networks:
      Backend:
        ipv4_adress: 172.28.1.1


  bwltool:
    build:
      context: .
    container_name: bwl-tool
    restart: always
    networks:
      Backend:
        ipv4_adress: 172.28.1.2
#      - Frontend

# In case you want to setup a traefik configuraion, you problably should close the ports     
    ports:
     - 80:8080
    
#    labels:
#      - traefik.enable=true
#      - traefik.http.routers.bwltoolRouter.rule=Host(`YOURDOMAIN.COM`)
#      - traefik.http.routers.bwltoolRouter.entrypoints=Https
#      - traefik.http.routers.bwltoolRouter.tls=true
#      - traefik.http.routers.bwltoolRouter.tls.certresolver=HttpsResolver

networks:
  Backend:
    external: false
    ipam:
      driver: default
      cronfig:
        - subnet: 172.28.0.0/16
#  Frontend:
#    external: true

